name: oct-cnn
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.1.0
  - absl-py=0.7.0
  - astor=0.7.1
  - blas=1.0
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cudatoolkit=9.0
  - cudnn=7.1.4
  - cycler=0.10.0
  - freetype=2.9.1
  - gast=0.2.2
  - grpcio=1.16.1
  - h5py=2.9.0
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - intel-openmp=2019.1
  - jpeg=9b
  - keras=2.2.4
  - keras-applications=1.0.6
  - keras-base=2.2.4
  - keras-preprocessing=1.0.5
  - kiwisolver=1.1.0
  - libpng=1.6.37
  - libprotobuf=3.6.1
  - libtiff=4.0.10
  - markdown=3.0.1
  - matplotlib=3.0.3
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - numpy-base=1.15.4
  - olefile=0.46
  - opencv=3.3.1
  - openssl=1.1.1d
  - pandas=0.24.2
  - patsy=0.5.1
  - pillow=6.1.0
  - pip=9.0.1
  - protobuf=3.6.1
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyreadline=2.1
  - python=3.6.8
  - python-dateutil=2.8.0
  - pytz=2019.1
  - qt=5.9.7
  - scikit-learn=0.20.3
  - seaborn=0.9.0
  - setuptools=40.6.3
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.26.0
  - statsmodels=0.9.0
  - tensorboard=1.12.2
  - tensorflow=1.12.0
  - tensorflow-base=1.12.0
  - termcolor=1.1.0
  - tk=8.6.8
  - tornado=6.0.2
  - vc=14.1
  - vs2015_runtime=14.15.26706
  - werkzeug=0.14.1
  - wheel=0.32.3
  - wincertstore=0.2
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - chardet==3.0.4
    - click==7.0
    - configparser==4.0.2
    - decorator==4.4.1
    - docker-pycreds==0.4.0
    - gitdb2==2.0.6
    - gitpython==3.0.7
    - gql==0.2.0
    - graphql-core==1.1
    - idna==2.8
    - imageio==2.6.1
    - networkx==2.4
    - numpy==1.18.1
    - nvidia-ml-py3==7.352.0
    - pathtools==0.1.2
    - promise==2.3
    - psutil==5.6.7
    - pywavelets==1.1.1
    - pyyaml==5.3
    - requests==2.22.0
    - scikit-image==0.16.2
    - scipy==1.4.1
    - sentry-sdk==0.14.1
    - shortuuid==0.5.0
    - smmap2==2.0.5
    - subprocess32==3.5.4
    - urllib3==1.25.8
    - wandb==0.8.25
    - watchdog==0.10.1